### ISSUE TITLE
COMPASS -- Jigsawpy module not found

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Model#321] opened 2019-07-07 03:37 UTC
On LANL IC, I am trying to run the EC60to30 test case.  I can set this up okay, but if I do run.py in the init folder, I get the following errors
```
 * Creating 2D global base mesh with jigsaw...
Traceback (most recent call last):
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_py3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_py3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/lustre/scratch4/turquoise/.mdt2/lvanroekel/MPAS-Model/testing_and_setup/compass/ocean/global_ocean/EC60to30/init/base_mesh/jigsaw_to_MPAS/build_mesh.py", line 23, in <module>
    from jigsaw_to_MPAS.jigsaw_driver import jigsaw_driver
  File "/lustre/scratch4/turquoise/.mdt2/lvanroekel/MPAS-Model/testing_and_setup/compass/ocean/global_ocean/EC60to30/init/base_mesh/jigsaw_to_MPAS/jigsaw_driver.py", line 5, in <module>
    import jigsawpy
ModuleNotFoundError: No module named 'jigsawpy'
Traceback (most recent call last):
  File "./run.py", line 16, in <module>
    subprocess.check_call(['python', '-m', 'jigsaw_to_MPAS.build_mesh'])
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_py3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'jigsaw_to_MPAS.build_mesh']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "./run.py", line 59, in <module>
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_py3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./run.py']' returned non-zero exit status 1.
```
This is with the suggested compass python environment in the readme.ocean file.

I also attempted to run the test case on blues/anvil, but in trying to create the conda environment, using
```
conda create -n compass_py3.7 -c conda-forge python=3.7 \
    geometric_features=0.1.1 mpas_tools=0.0.3 jigsaw=0.9.10 jigsawpy=0.0.2 \
    metis pyflann scikit-image basemap pyamg ffmpeg
```
I get the following error
```
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - jigsawpy=0.0.2

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```
It seems there is an issue with jigsawpy.  This is ocean/develop in both cases.  I would appreciate any help.  Please let me know if you need more information.

**Comment by xylar** [comment] 2019-07-07 08:06
@vanroekel, this is 100% my fault.  I was away on travel and wasn't paying close enough attention when i approved #301.  It should not have been merged until jigsawpy got released, which has not happened yet.  We have been working with a test build of the `dev` branch for #301.  I will try to figure out why the environment with the test build is not working for you on IC but that at least explains why you couldn't set up on Anvil.  I'm sorry about this.

@dengwirda, do you have an estimate on when you might be ready for the first release of jigsaw-geo-python?  If you're not quite ready, we should probably revert #301 for now.

**Comment by xylar** [comment] 2019-07-07 08:25
@vanroekel, an update.  I agree that I'm not seeing `jigsawpy` in the `compass_py3.7` environment on LANL IC.  I'm also not able to clone it at the moment to make a local build -- GitHub access from IC seems to be blocked.  Again, I'm sorry about this and I'll try to fix it as soon as I can.

**Comment by xylar** [comment] 2019-07-07 09:03
I've installed a local build of `jigsawpy` on LANL IC.  However, I'm unable to test because ssh is currently not reaching github.com on Grizzly.  If the problem persists tomorrow, I'll check with support.

I'm currently trying to building a `compass_py3.7` environment on Anvil, but I'm running into (seemingly network-related) trouble there as well.

**Comment by xylar** [comment] 2019-07-07 09:23
I installed the `compass_py3.7` environment on Anvil.  It can be accessed with:
```
source /lcrc/soft/climate/e3sm-unified/load_compass_py3.7
```

**Comment by xylar** [comment] 2019-07-07 09:32
This issue should remain open until `jigsawpy` has been released and the definition of the COMPASS environment has been updated accordingly.  For example, `jigsaw=0.9.11` is currently required for the test version of `jigsawpy=0.0.2`.

**Comment by vanroekel** [comment] 2019-07-08 04:39
@xylar thanks for the quick fix!  I was able to setup the EC6030 on blues/anvil, even on compute nodes.

**Comment by xylar** [comment] 2019-07-08 09:03
@vanroekel, I'm glad things are working for you on Anvil.  Thanks for pointing out these issues before they became more problematic.

@mark-petersen, @sbrus89, @pwolfram and others, I think we probably don't need to revert #301 but we do need to be careful that we don't create any new jigsaw meshes that will be used in any lasting simulation campaigns until `jigsawpy` gets an official release.  Otherwise, it could be that our meshes are hard to reproduce.

**Comment by dengwirda** [comment] 2019-07-08 11:57
Hi all, just confirming that a non-`dev` `jigsawpy` release should be available later this week - I'm currently working to include the "gradient-limiting" solvers in the `python` interface so that a full workflow is available.

This involves moving several things from the `matlab` to `c++` layers and making them available via the `cmd-line` and `api` interfaces. Shouldn't result in any changes to the current `jigsawpy` workflow, just adds new functionality.

Access to the gradient-limiters is not needed for standard meshes (`EC60-to-30`, etc), but will be required for more complex config.'s that build mesh-spacing information from data directly.

**Comment by xylar** [comment] 2019-07-08 12:36
@dengwirda, that all sounds great, thanks!

**Comment by mark-petersen** [comment] 2019-12-11 21:35
This issue is solved. See documentation at https://acme-climate.atlassian.net/wiki/spaces/ECG/pages/1054113803/MPAS-Ocean+Initialization+and+Testing

**Closed by mark-petersen** 2019-12-11 21:35 UTC
Labels: COMPASS, Ocean, bug
