### ISSUE TITLE
V7.0: Undefined vars "Active" in core_atmosphere/inc/structs_and_variables.inc

### ISSUE THREAD

**Issue by cd10kfsu** [MPAS-Dev/MPAS-Model#283] opened 2019-06-17 05:28 UTC
For MPAS version 7.0, there is an undefined var "Active" in core_atmosphere/inc/structs_and_variables.inc (Line 16656). I tried MPAS version 6.3, and it doesn't have this problem. The error is attached below:

./inc/structs_and_variables.inc:16656:16:
       if (Active .or. mp_wsm6_inActive) then
                1
Error: Symbol ‘active’ at (1) has no IMPLICIT type
./inc/structs_and_variables.inc:8812:16:
       if (Active .or. mp_thompson_inActive) then
                1
Error: Symbol ‘active’ at (1) has no IMPLICIT type

The title above should be a 1 line short summary of the issue.

Enter a description of the issue.
This should include what the symptoms are, and steps to reproduce.

Additionally please enter this information if applicable:
 - Compiler and version
 - MPI implementation and version
 - NetCDF version
 - Parallel NetCDF version
 - Parallel IO version
 - Output of `uname -a`
 - The make line used to build the executable
 - The line used to run the executable
 - Test case used

**Comment by cd10kfsu** [comment] 2019-06-17 05:32
The corresponding lines in V6.3 is 21568-21574:
21568       if (iauActive .or. bl_mynn_inActive .or. bl_ysu_inActive .or. cu_tiedtke_inActive .or.       mp_kessler_inActive .or. &
21569 mp_thompson_inActive .or. mp_wsm6_inActive) then
21570          r3Ptr(1) % isActive = .true.
21571       end if
21572       call mpas_pool_add_field(newSubPool, 'scalars', r3Ptr)
21573       call mpas_pool_add_field(block % allFields, 'scalars_amb', r3Ptr)
21574

**Comment by mgduda** [comment] 2019-06-18 17:19
@cd10kfsu So far I'm not able to reproduce this issue locally.
* Which compiler and compiler version are you using when you encounter this error?
* Have you made any changes at all to the `master` branch of the `MPAS-Model` repository?
* If you run `make clean CORE=atmosphere` and re-compile, does that resolve the issue?

**Comment by cd10kfsu** [comment] 2019-06-18 18:15
I successfully compiled atmosphere_model (V7.0) on my other laptop. So the problem lies on my side. I will debug that part by myself. Sorry for wasting your time. Thank you for your kind and swift help.

**Comment by mgduda** [comment] 2019-06-18 18:23
I'll close this issue for now. But, if you do find anything in your debugging that points to a problem with the code, please feel free to re-open this issue and I'll be glad to help.

**Closed by mgduda** 2019-06-18 18:23 UTC
Labels: Atmosphere
