### ISSUE TITLE
In Compass, path to model invalid with MPICH 3.3a2

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#50] opened 2018-05-30 18:50 UTC
When I run a Compass test case with MPICH 3.3a2 installed on my laptop (running Ubuntu 18.04), I get the error (the first line repeated once for each MPI task):
```
[proxy:0:0@eleven] HYDU_create_process (utils/launch/launch.c:74): execvp error on file ocean_model (No such file or directory)
Traceback (most recent call last):
  File "./run.py", line 37, in <module>
    'namelist.ocean', '-s', 'streams.ocean'])
  File "/home/xylar/miniconda3/envs/mpas/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '-n', '4', 'ocean_model', '-n', 'namelist.ocean', '-s', 'streams.ocean']' returned non-zero exit status 255
```

The solution seems to be changing from `ocean_model` to `./ocean_model`.

I was able to get this result by changing this line:
https://github.com/MPAS-Dev/MPAS-Model/blob/master/testing_and_setup/compass/setup_testcase.py#L1086
as follows
```
-                        grandchild.text = executable_link
+                        grandchild.text = './{}'.format(executable_link)
```

Before I make a pull request, I thought I'd get feedback on whether this is an issue others have run into and also whether this fix seems appropriate.

**Comment by xylar** [comment] 2018-05-30 18:52
@mark-petersen, @matthewhoffman, @vanroekel and @pwolfram, you seem the most likely to have run into this problem.  Does it look familiar or am I deviating from known recipes by using MPICH?

**Comment by pwolfram** [comment] 2018-05-30 18:54
My understanding is that MPICH is to be supported.  I vaguely recall running into this issue a long time ago in grad school and I believe I did what you did here.  

If you check for the executable "x" bit on ocean_model is it there?  I think this is a pretty strange issue but don't believe the `./ocean_model` syntax will cause a problem in general.

**Comment by xylar** [comment] 2018-05-30 19:02
> If you check for the executable "x" bit on ocean_model is it there?
```
-rwxr-xr-x  1 xylar xylar  11M May 30 19:45 ocean_model
```
Yep, that's not it.

**Comment by vanroekel** [comment] 2018-05-30 19:33
First, I have used mpich2 previously to build/run MPAS without issue.  I don't recall seeing this issue, but I think I may have always invoked with ./ocean_model

**Comment by mgduda** [comment] 2018-05-30 19:53
It's possible that the issue is just that "." is not in your path (and many argue it shouldn't be). If you run
```
export PATH=.:$PATH
```
(or the equivalent for csh/tcsh) are there any issues?

**Comment by matthewhoffman** [comment] 2018-05-30 19:54
@xylar , is this issue related to these files in any way?
https://github.com/MPAS-Dev/MPAS-Model/tree/master/testing_and_setup/compass/runtime_definitions

**Comment by xylar** [comment] 2018-05-30 21:38
@mgduda, I am firmly in the camp that doesn't think having '.' in your path is a good move.  I'd prefer not to have to go with that solution.

**Comment by xylar** [comment] 2018-05-30 21:39
@matthewhoffman, I looked into those files but they don't actually give you a way to add the './' that I can see.  This would have to be done in `setup_testcase.py` (at least as currently written).

**Comment by xylar** [comment] 2018-06-01 20:52
I'm running into this exact same problem on Edison and Cori with MPICH so I think it's an issue that really needs to be solved.  @mark-petersen, please let me know if you *don't* see this issue when you test next week.

**Comment by pwolfram** [comment] 2018-08-03 18:39
I'm having this issue with mpich on my side too @xylar.  A simple fix is to adapt compass as you list above.  I'm in strong support of this solution since it doesn't, as far as I can tell, have a side effect.

**Comment by pwolfram** [comment] 2018-08-03 18:44
@xylar, I took the liberty of just making a PR for this issue.  If there isn't any group-wide disagreement, I think we can just merge #60 and close this issue.  This only affects COMPASS on the ocean side.

**Comment by xylar** [comment] 2018-08-05 00:28
#60 is intended to address this.

**Closed** 2018-08-09 13:28 UTC
Labels: Compass
